# Generated by Django 3.1.7 on 2021-04-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_auto_20210402_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='hijode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.padre'),
        ),
    ]
